# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shublog', '0002_auto_20170911_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '\u6587\u7ae0', 'verbose_name_plural': '\u6587\u7ae0'},
        ),
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(default='anonymous', editable=False, max_length=128, verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_original',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u539f\u521b'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_publish',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u63a8\u8350'),
        ),
        migrations.AlterField(
            model_name='article',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='\u6807\u9898'),
        ),
    ]
