# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 09:05
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shublog', '0004_auto_20170911_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Content',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='content'),
        ),
    ]
